INCLUDES  = -I../../module_pcapng/src -I../common
INCLUDES += -I../../../sc_ethernet/tests/test_mii_dc/src

all:
	gcc -O2 ../common/shared.c traffic_gen_controller.c -o traffic_gen_controller $(INCLUDES)

